### ISSUE TITLE
upload them onto zenodo @qyx268

### ISSUE THREAD

**Issue by qyx268** [smutch/meraxes#92]

**Comment by s-balu** [comment]
can you share the zenodo link here?

**Comment by qyx268** [comment]
It's the same id as before. But here is it: https://zenodo.org/records/10608236

**Comment by qyx268** [comment]
@smutch @EMventura  I had to publish the trees before ppl can see the record. It's here and the metadata can still be updated. Please lemme know if you would like to change anything https://zenodo.org/records/10608236

**Comment by EMventura** [comment]
Awesome! Thank you!

**Comment by qyx268** [comment]
I've not closed this ticket as the file's md5 hash has changed and the download speed from Zenodo is 250kb/s despite speedtest says >150Mb/s... I'm following up with Zenodo.

**Comment by qyx268** [comment]
done! 
They redownloaded and uploaded the file again and now the hash key is identical to the original file. 

About the speed, they said they don't put any limit. I've also downloaded at ANU and the speed was decent
